### ISSUE TITLE
Update to MVS pypi release

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#142]
Now MVS really is on pypi - with version v0.5.2 :) before there was just a release candidate (rc). 

todos:
- [ ] update setup requirements of pvcompare to new version @SabineHaas 
- [ ] delete label parameter in all csv input file templates / PARAMTERS section (except `fix_costs`) @SabineHaas 
- [ ] check whether changes in [MVS#596](https://github.com/rl-institut/multi-vector-simulator/pull/596) affect simulation results with heat pump (if not done, yet, as this change has been on the `dev` of MVS for a while already) @MaGering  **
- [ ] rename `minimal_renewable_share` to `minimal_renewable_factor` in contraint csvs @SabineHaas 

todos, changes when PRs merged and released:
- [ ] add `energyBusses.csv` to input file templates @SabineHaas  ([MVS #649](https://github.com/rl-institut/multi-vector-simulator/pull/649/files))
- [ ] Feed-in tariff has to be positve now @SabineHaas ([MVS #670](https://github.com/rl-institut/multi-vector-simulator/pull/670))

** @MaGering The changes here were that  `variable_costs`, `efficiency` and `nominal_value` of transformers were assigned on output flows, which was not always the case before. Maybe we can discuss this in a call next week, as this issue might not be very clear to you now.
