### ISSUE TITLE
todo december 2020

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#169]
**Important tasks:**

General issues:

- [x] (IS): update to cpvlib tag: 2020-11 (1)

- [x] (IS): new method for calculating DHI #193 (1)

- [x] (IS): delete SH from electricity demand #196 (1)

- [x] (IS): Define efficient output structure #147 (1) 

- :x: (IS): finalize Normalization #168 (1) #200

- [x] (IS): Pvcompare main / run_pvcompare #164 (1)

- [x] (IS): [outputs] add plotting function that compares pv technologies #166

- [x] (SH): Check lifetime of inverter and charge controller #62 

- [x] (IS): [pvcompare] finalize PV costs #170 (1)

- [x] (IS): [pvcompare] loop over different weather years #171 [decision wanted]

- [x] (IS): [pvcompare] write function to loop over pvcompare parameters #172

- [x] (IS): Generalize `check_inputs.add_parameters_to_energy_production_file()` #152 (2)

- [x] (IS): add function that fills in default values for different PV technologies #180 (2)

PV-HP issues

- [x] (MG): [PV HP] definition of heating/cooling period #60 (1)

- [x] (MG): [PV HP] Finish tests for heat pumps and chillers #66 (3)

Minor fixes (fast and/or easy):

- [x] (SH) Suppress showing of plots as this is unhandy when running pytests #173 (1)

- [x] (IS) Hand over `mvs_input_directory` to functions that are called within a function #102

- [x] (IS):  update function add_energy_price #116 

later todo:

- [x] (IS): rework check_inputs module #167

- :x: all: see projekt Documentation: https://github.com/greco-project/pvcompare/projects/1#card-50555881 (3) --> future tasks

**Comment by SabineHaas** [comment]
@Piranias is it okay if I just add points by editing your post?

**Comment by Piranias** [comment]
> @Piranias is it okay if I just add points by editing your post?

yes, please!

**Comment by SabineHaas** [comment]
I also tried to define some priorities, ranking behind the PR numbers with (1), (2), ...
