### ISSUE TITLE
Release v0.0.3

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#304]
- [x] first of all, fix #314
- [x] merge #323
- [x] merge #309
- [x] adapt/check date in changelog.md
- [x] use existing release branch, merge dev into release branch before going on with release protocol
- :x: check whether #305 solves #297, otherwise solve.
- [x] make sure #298 really solves #296 
- [x] make sure that all wanted changes are included
- [x] check zenodo doi, add badge to readme #282
- [x] add contributors to zenodo (for citation)

**Comment by SabineHaas** [comment]
@Piranias @MaGering 
which changes would you like to include into release v0.0.3? --> please refer to issues

- I would prefer to do the release as soon as possible, to fix master build and to get a DOI in Zenodo. 
- This could already be the release for @MaGering 's thesis.. ? If you prefer improved code documentation + RTD, we should have one in between, before code changes.
- The tag of this release (befor code changes) will also be the reference for our working paper (version that was used for simulations), right @Piranias ?
- We should do another release end of May for the final meeting, that will still improve the documentation, include fixed issues and update to newest MVS version if possible (also changes in code). 

please let me know whether you agree.

**Comment by SabineHaas** [comment]
@MaGering I have edited the zenodo upload now: contributors, title, description, license..
